(cl:defpackage e190_bot-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "PATH_SERVICE"
   "<PATH_SERVICE-REQUEST>"
   "PATH_SERVICE-REQUEST"
   "<PATH_SERVICE-RESPONSE>"
   "PATH_SERVICE-RESPONSE"
  ))

